services:
  db:
    image: mariadb:11
    container_name: nocountry_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3305:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    image: danielmchachagua/apinocountry:0.0.6
    container_name: nocountry_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3001:3001"

volumes:
  db_data:

